### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by shani1610** [AryamanSharma17/ScenRec#1]
in grounding Dino line 6 i got this error:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?534b244f-a9e3-46db-af78-2c510c87b36d) or open in a [text editor](command:workbench.action.openLargeOutput?534b244f-a9e3-46db-af78-2c510c87b36d). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by AryamanSharma17** [comment]
Can you send me the which files code did you get error in?
